import jsPDF from 'jspdf';

export interface OfferApplicant {
  refNo: string;
  personal: { name: string; fatherName: string };
  allocatedProgramName?: string;
  preferences: { programName: string; rank: number }[];
  meritScore?: number;
}

const PRIMARY: [number, number, number] = [30, 58, 95];

export function downloadOfferLetterPdf(applicant: OfferApplicant, orgName: string): void {
  const doc = new jsPDF('portrait', 'mm', 'a4');
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const m = 22;
  const cw = W - m * 2;
  let y = 15;

  const issueDate = new Date().toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' });
  const program = applicant.allocatedProgramName ?? applicant.preferences[0]?.programName ?? 'Selected Program';

  // Header
  doc.setFillColor(...PRIMARY);
  doc.rect(m, y, cw, 28, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(255, 255, 255);
  doc.text(orgName, W / 2, y + 11, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(200, 220, 255);
  doc.text('OFFER OF ADMISSION', W / 2, y + 20, { align: 'center' });
  y += 34;

  // Ref & Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(110, 110, 110);
  doc.text(`Ref: ${applicant.refNo}`, m, y);
  doc.text(`Date: ${issueDate}`, W - m, y, { align: 'right' });
  y += 12;

  // Greeting
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(35, 35, 35);
  const greeting = `Dear ${applicant.personal.name},`;
  doc.text(greeting, m, y);
  y += 9;

  const para1 = `We are pleased to inform you that you have been selected for admission to ${orgName}. Following a review of your application and academic performance, you have been allocated a seat in the program specified below.`;
  const split1 = doc.splitTextToSize(para1, cw);
  doc.text(split1, m, y);
  y += split1.length * 5.5 + 10;

  // Program box
  doc.setFillColor(245, 248, 255);
  doc.setDrawColor(...PRIMARY);
  doc.roundedRect(m, y, cw, 30, 3, 3, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...PRIMARY);
  doc.text(program, W / 2, y + 13, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(80, 80, 80);
  doc.text(`Applicant: ${applicant.personal.name}  ·  Father: ${applicant.personal.fatherName}`, W / 2, y + 22, { align: 'center' });
  y += 38;

  // Action required
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(180, 30, 30);
  doc.text('ACTION REQUIRED:', m, y);
  y += 6;

  const steps = [
    '1. Report to the institution office within 7 working days of this notice.',
    '2. Bring original documents: B-Form/CNIC, Result Card, 2 passport photographs.',
    '3. Pay the admission fee at the fee counter or via online payment.',
    '4. Failure to report within the deadline will forfeit your seat.',
  ];
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(35, 35, 35);
  for (const step of steps) {
    const split = doc.splitTextToSize(step, cw);
    doc.text(split, m, y);
    y += split.length * 5 + 2;
  }
  y += 8;

  // Closing
  const closing = 'We congratulate you on your selection and look forward to welcoming you to our institution.';
  const splitClose = doc.splitTextToSize(closing, cw);
  doc.text(splitClose, m, y);
  y += splitClose.length * 5.5 + 16;

  // Signature blocks
  const sigW = (cw - 20) / 2;
  ['Admission Officer', 'Principal'].forEach((title, i) => {
    const sx = m + i * (sigW + 20);
    doc.setDrawColor(180, 180, 180);
    doc.line(sx, y + 14, sx + sigW, y + 14);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 100, 100);
    doc.text(title, sx + sigW / 2, y + 20, { align: 'center' });
    doc.text('Signature & Stamp', sx + sigW / 2, y + 25, { align: 'center' });
  });
  y += 32;

  // Important note
  doc.setFillColor(255, 251, 230);
  doc.setDrawColor(230, 190, 60);
  doc.roundedRect(m, y, cw, 12, 2, 2, 'FD');
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7.5);
  doc.setTextColor(120, 90, 0);
  doc.text('This offer is conditional upon verification of original documents and does not constitute final enrollment.', W / 2, y + 8, { align: 'center' });

  // Footer
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(190, 190, 190);
  doc.text('Generated by EduStack PK — WolfStack', W / 2, H - 9, { align: 'center' });
  doc.text('This is a computer-generated document.', W / 2, H - 5, { align: 'center' });

  doc.save(`OfferLetter_${applicant.personal.name.replace(/\s+/g, '_')}_${applicant.refNo}.pdf`);
}
