import jsPDF from 'jspdf';

export interface ProvisionalApplicant {
  refNo: string;
  personal: { name: string; fatherName: string; dob?: string; gender?: string };
  allocatedProgramName?: string;
  preferences: { programName: string; rank: number }[];
}

const PRIMARY: [number, number, number] = [30, 58, 95];

export function downloadProvisionalCertPdf(applicant: ProvisionalApplicant, orgName: string): void {
  const doc = new jsPDF('portrait', 'mm', 'a4');
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const m = 22;
  const cw = W - m * 2;
  let y = 15;

  const issueDate = new Date().toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' });
  const certNo = `PROV-${applicant.refNo}-${new Date().getFullYear()}`;
  const program = applicant.allocatedProgramName ?? applicant.preferences[0]?.programName ?? '—';

  // Header
  doc.setFillColor(...PRIMARY);
  doc.rect(m, y, cw, 30, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(255, 255, 255);
  doc.text(orgName, W / 2, y + 11, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(200, 220, 255);
  doc.text('PROVISIONAL ADMISSION CERTIFICATE', W / 2, y + 21, { align: 'center' });
  y += 38;

  // Cert No & Date
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(100, 100, 100);
  doc.text(`Cert No: ${certNo}`, m, y);
  doc.text(`Issue Date: ${issueDate}`, W - m, y, { align: 'right' });
  y += 14;

  // Certification text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(35, 35, 35);
  const certText = `This is to certify that the following candidate has been provisionally admitted to ${orgName} for the academic session. This certificate is subject to verification of original documents and payment of admission dues.`;
  const split = doc.splitTextToSize(certText, cw);
  doc.text(split, m, y);
  y += split.length * 5.5 + 12;

  // Details table
  const rows: [string, string][] = [
    ["Candidate's Name", applicant.personal.name],
    ["Father's Name", applicant.personal.fatherName],
    ['Program Admitted', program],
    ['Application Ref No', applicant.refNo],
    ['Date of Birth', applicant.personal.dob ? new Date(applicant.personal.dob).toLocaleDateString('en-PK') : '—'],
    ['Gender', applicant.personal.gender ? applicant.personal.gender.charAt(0).toUpperCase() + applicant.personal.gender.slice(1) : '—'],
    ['Issue Date', issueDate],
    ['Status', 'PROVISIONAL — Subject to document verification'],
  ];

  const labelW = 65;
  const rowH = 9;

  for (let i = 0; i < rows.length; i++) {
    const [label, value] = rows[i];
    const bg: [number, number, number] = i % 2 === 0 ? [255, 255, 255] : [248, 250, 252];
    doc.setFillColor(...bg);
    doc.rect(m, y, cw, rowH, 'F');
    doc.setDrawColor(225, 225, 225);
    doc.rect(m, y, cw, rowH);

    // Label
    doc.setFillColor(235, 241, 252);
    doc.rect(m, y, labelW, rowH, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(55, 75, 115);
    doc.text(label, m + 3, y + 6);

    // Value
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(30, 30, 30);
    doc.text(String(value), m + labelW + 4, y + 6);
    y += rowH;
  }
  y += 16;

  // Conditions
  doc.setFillColor(250, 250, 250);
  doc.setDrawColor(220, 220, 220);
  doc.rect(m, y, cw, 28, 'FD');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(60, 60, 60);
  doc.text('Conditions of Provisional Admission:', m + 4, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(80, 80, 80);
  const conditions = [
    '• Submit all original documents within 15 days.',
    '• Pay admission fee within 7 working days.',
    '• This certificate does not guarantee final enrollment.',
    '• Institution reserves the right to cancel admission if documents are found incorrect.',
  ];
  let cy = y + 13;
  for (const c of conditions) {
    doc.text(c, m + 4, cy);
    cy += 5;
  }
  y += 34;

  // Signature blocks
  const sigW = (cw - 20) / 2;
  ['Issuing Authority', 'Principal / Director'].forEach((title, i) => {
    const sx = m + i * (sigW + 20);
    doc.setDrawColor(170, 170, 170);
    doc.line(sx, y + 14, sx + sigW, y + 14);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(100, 100, 100);
    doc.text(title, sx + sigW / 2, y + 20, { align: 'center' });
    doc.text('Signature & Stamp', sx + sigW / 2, y + 25, { align: 'center' });
  });

  // Footer
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(7);
  doc.setTextColor(190, 190, 190);
  doc.text('Generated by EduStack PK — WolfStack  |  This is a computer-generated document.', W / 2, H - 7, { align: 'center' });

  doc.save(`ProvisionalCert_${applicant.personal.name.replace(/\s+/g, '_')}_${applicant.refNo}.pdf`);
}
